export const FETCH_USER_TRANSACTIONS = "FETCH_USER_TRANSACTIONS"
export const FETCH_USER_TRANSACTION =  "FETCH_USER_TRANSACTION"
// ACCOUNTS
export const ADD_ACCOUNT = "ADD_ACCOUNT"

//TRANSACTIONS
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const SET_TRANSACTION_VALUE = "SET_TRANSACTION_VALUE";

//USERS
export const LOGIN_USER = "LOGIN_USER";


