// ACCOUNTS
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const GET_USER_ACCOUNTS = "GET_USER_ACCOUNTS";
export const GET_USER_SINGLE_ACCOUNT = "GET_USER_SINGLE_ACCOUNT";
export const FETCH_BANKS = "FETCH_BANKS";
export const SET_MAIN_ACCOUNT = "SET_MAIN_ACCOUNT";

//TRANSACTIONS
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const SET_TRANSACTION = "SET_TRANSACTION";
export const SET_TRANSACTION_VALUE = "SET_TRANSACTION_VALUE";
export const FETCH_USER_TRANSACTIONS = "FETCH_USER_TRANSACTIONS";
export const FETCH_USER_TRANSACTION = "FETCH_USER_TRANSACTION";
export const FETCH_AGENT_TRANSACTIONS = "FETCH_AGENT_TRANSACTIONS";
export const SET_AG_TRANSACTION_VALUE = "SET_AG_TRANSACTION_VALUE";

//USERS
export const LOGIN_USER = "LOGIN_USER";
export const MODE = "MODE";
//AGENTS
export const CREATE_AGENT = "CREATE_AGENT";
export const SET_AGENT = "SET_AGENT";
export const CREATE_STORE = "CREATE_STORE";
export const SET_AGENTS = "SET_AGENTS";

//TOKEN
export const TOKEN = "TOKEN";
