export const FETCH_USER_TRANSACTIONS = "FETCH_USER_TRANSACTIONS";
export const FETCH_USER_TRANSACTION = "FETCH_USER_TRANSACTION";
// ACCOUNTS
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const GET_USER_ACCOUNTS = "GET_USER_ACCOUNTS";

//TRANSACTIONS
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const SET_TRANSACTION = "SET_TRANSACTION";

//USERS
export const LOGIN_USER = "LOGIN_USER";

//AGENTS

export const SET_AGENT = "SET_AGENT";
