import { StyleSheet } from "react-native";
import { headerColor, buttonDark, textButtonDark, cardDark, headerColorDark, movimientosDark } from "../../Common/constans";

export const style = StyleSheet.create({
  mainContainer:{ 
    flex: 1, 
    alignItems: "center" 
  },
  container: {
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      height: '50%',
      width: '90%',
      // borderWidth: 1,
      // borderColor: 'red'
  },
  agente: {
    width: '45%',
    height:'45%',
    backgroundColor: "white",
    margin: '2%',
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 6,
    shadowColor: "#000",
    // borderWidth: 1,
    // borderColor: 'blue',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8.0,
    elevation: 5,
  },
  movimientos: {
    fontSize: 30,
    marginTop: '2%',
    marginBottom: '2%',
    textAlign: "center",
    fontFamily: "nunito",
    color: `${headerColor}`,
  },
  movimientosDark: {
    fontSize: 30,
    marginTop: '2%',
    marginBottom: '2%',
    textAlign: "center",
    fontFamily: "nunito",
    color: movimientosDark,
  },

  movimientosContainer: {
    flex: 1,
    backgroundColor: "white",
    borderTopRightRadius: 28,
    borderTopLeftRadius: 28,
    width: "94%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8.0,
    elevation: 5,
  },
  movimientosContainerDark: {
    flex: 1,
    backgroundColor: headerColorDark,
    borderTopRightRadius: 28,
    borderTopLeftRadius: 28,
    width: "94%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8.0,
    elevation: 5,
  },
  agenteDark: {
    width: 150,
    height:140,
    backgroundColor: buttonDark,
    margin: '2%',
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 6,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8.0,
    elevation: 5,
  },
  imageIconStyle: {
    padding: 10,
    height: 65,

    width: 65,
    resizeMode: "stretch",
  },
  text: {
    textAlign: "center",
    color: "black",
    fontSize: 14,
    textTransform: "uppercase",
    //fontFamily: "sans-serif",
    marginTop: '2%',
  },
  textDark: {
    textAlign: "center",
    color: textButtonDark,
    fontSize: 14,
    textTransform: "uppercase",
    //fontFamily: "sans-serif",
    marginTop: '2%',
  },
  hr: {
    borderBottomColor: "#DDDDDD",
    borderBottomWidth: 1,
    display: "flex",
    alignSelf: "center",
    width: "100%",
    marginBottom: '1%',
    marginTop: '1%',
  },
  time: {
    color: "#A8C3EC",
    fontSize: 17,
    textAlign: "center",
    marginBottom: '2%',
  },
  single: {
    backgroundColor: "#F4F9FE" /* #629bcaa6 */,
    flexDirection: "row",
    height: '10%',
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 10,
    flex: 1,
    elevation:2,
    marginBottom:'1%'
  },
  singleDark: {
    backgroundColor: cardDark /* #629bcaa6 */,
    flexDirection: "row",
    height: '10%',
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 10,
    flex: 1,
    elevation:2,
    marginBottom:'1%'
  },
  contenido: {
    flex: 3,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  monto: {
    flex: 2,
    alignItems: "center",
    height: "100%",
    justifyContent: "center",
  },
  montoTexto: {
    fontFamily: "lato",
    fontSize: 21,
    color: headerColor,
    marginLeft: 20,
  },
  montoTextoDark: {
    fontFamily: "lato",
    fontSize: 21,
    color: "white",
    marginLeft: 20,
  },
  entrar: {
    flex: 1,
    alignItems: "flex-end",
    height: "100%",
    justifyContent: "center",
    marginRight: 5,
  },
  /* textoContenido: {
    fontFamily: "lato",
    fontSize: 16,
    color: "#3D5E87",
    alignSelf: "flex-start",
    paddingLeft: 20,
    marginBottom:3
  }, */
});
